-- -------------------------------------------------------------
--
-- Module: CIC2_V3
-- Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
-- Generated on: 2022-12-21 10:46:42
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- FIRAdderStyle: tree
-- OptimizeForHDL: on
-- TargetDirectory: C:\Users\Elia Yfrach\Desktop\Project\Processing_Unit\Filters
-- AddPipelineRegisters: on
-- Name: CIC2_V3
-- TestBenchName: CIC2_V3_tb
-- TestBenchStimulus: step ramp chirp noise 
-- GenerateHDLTestBench: off

-- Filter Specifications:
--
-- Sample Rate        : 45.955 kHz
-- Response           : CIC Compensator
-- Specification      : Fp,Fst,Ap,Ast
-- Decimation Factor  : 10
-- Multirate Type     : Decimator
-- Stopband Edge      : 2.3 kHz
-- Passband Edge      : 150 Hz
-- Stopband Atten.    : 10 dB
-- Number of Sections : 2
-- Passband Ripple    : 1 dB
-- Differential Delay : 1
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Multirate Filter (real)
-- -----------------------------------------
-- Filter Structure   : Direct-Form FIR Polyphase Decimator
-- Decimation Factor  : 10
-- Polyphase Length   : 2
-- Filter Length      : 13
-- Stable             : Yes
-- Linear Phase       : Yes (Type 1)
--
-- Arithmetic         : fixed
-- Numerator          : s17,18 -> [-2.500000e-01 2.500000e-01)
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY CIC2_V3 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(16 DOWNTO 0); -- sfix17_En9
         filter_out                      :   OUT   std_logic_vector(34 DOWNTO 0); -- sfix35_En27
         ce_out                          :   OUT   std_logic  
         );

END CIC2_V3;


----------------------------------------------------------------
--Module Architecture: CIC2_V3
----------------------------------------------------------------
ARCHITECTURE rtl OF CIC2_V3 IS
  -- Local Functions
  -- Type Definitions
  TYPE input_pipeline_type IS ARRAY (NATURAL range <>) OF signed(16 DOWNTO 0); -- sfix17_En9
  TYPE sumdelay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(34 DOWNTO 0); -- sfix35_En27
  -- Constants
  CONSTANT coeffphase1_1                  : signed(16 DOWNTO 0) := to_signed(42637, 17); -- sfix17_En18
  CONSTANT coeffphase1_2                  : signed(16 DOWNTO 0) := to_signed(13926, 17); -- sfix17_En18
  CONSTANT coeffphase2_1                  : signed(16 DOWNTO 0) := to_signed(12538, 17); -- sfix17_En18
  CONSTANT coeffphase2_2                  : signed(16 DOWNTO 0) := to_signed(12538, 17); -- sfix17_En18
  CONSTANT coeffphase3_1                  : signed(16 DOWNTO 0) := to_signed(13926, 17); -- sfix17_En18
  CONSTANT coeffphase3_2                  : signed(16 DOWNTO 0) := to_signed(42637, 17); -- sfix17_En18
  CONSTANT coeffphase4_1                  : signed(16 DOWNTO 0) := to_signed(15063, 17); -- sfix17_En18
  CONSTANT coeffphase4_2                  : signed(16 DOWNTO 0) := to_signed(0, 17); -- sfix17_En18
  CONSTANT coeffphase5_1                  : signed(16 DOWNTO 0) := to_signed(15917, 17); -- sfix17_En18
  CONSTANT coeffphase5_2                  : signed(16 DOWNTO 0) := to_signed(0, 17); -- sfix17_En18
  CONSTANT coeffphase6_1                  : signed(16 DOWNTO 0) := to_signed(16477, 17); -- sfix17_En18
  CONSTANT coeffphase6_2                  : signed(16 DOWNTO 0) := to_signed(0, 17); -- sfix17_En18
  CONSTANT coeffphase7_1                  : signed(16 DOWNTO 0) := to_signed(16643, 17); -- sfix17_En18
  CONSTANT coeffphase7_2                  : signed(16 DOWNTO 0) := to_signed(0, 17); -- sfix17_En18
  CONSTANT coeffphase8_1                  : signed(16 DOWNTO 0) := to_signed(16477, 17); -- sfix17_En18
  CONSTANT coeffphase8_2                  : signed(16 DOWNTO 0) := to_signed(0, 17); -- sfix17_En18
  CONSTANT coeffphase9_1                  : signed(16 DOWNTO 0) := to_signed(15917, 17); -- sfix17_En18
  CONSTANT coeffphase9_2                  : signed(16 DOWNTO 0) := to_signed(0, 17); -- sfix17_En18
  CONSTANT coeffphase10_1                 : signed(16 DOWNTO 0) := to_signed(15063, 17); -- sfix17_En18
  CONSTANT coeffphase10_2                 : signed(16 DOWNTO 0) := to_signed(0, 17); -- sfix17_En18

  -- Signals
  SIGNAL ring_count                       : unsigned(9 DOWNTO 0); -- ufix10
  SIGNAL phase_0                          : std_logic; -- boolean
  SIGNAL phase_1                          : std_logic; -- boolean
  SIGNAL phase_2                          : std_logic; -- boolean
  SIGNAL phase_3                          : std_logic; -- boolean
  SIGNAL phase_4                          : std_logic; -- boolean
  SIGNAL phase_5                          : std_logic; -- boolean
  SIGNAL phase_6                          : std_logic; -- boolean
  SIGNAL phase_7                          : std_logic; -- boolean
  SIGNAL phase_8                          : std_logic; -- boolean
  SIGNAL phase_9                          : std_logic; -- boolean
  SIGNAL ce_out_reg                       : std_logic; -- boolean
  SIGNAL input_register                   : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase0            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase1            : input_pipeline_type(0 TO 1); -- sfix17_En9
  SIGNAL input_pipeline_phase2            : input_pipeline_type(0 TO 1); -- sfix17_En9
  SIGNAL input_pipeline_phase3            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase4            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase5            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase6            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase7            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase8            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL input_pipeline_phase9            : signed(16 DOWNTO 0); -- sfix17_En9
  SIGNAL tapsum1                          : signed(17 DOWNTO 0); -- sfix18_En9
  SIGNAL product_phase0_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase0_2                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase1_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase1_2                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase2_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase2_2                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase3_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase4_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase5_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase6_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase7_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase8_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_phase9_1                 : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase0_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase0_2        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase1_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase1_2        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase2_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase2_2        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase3_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase4_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase5_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase6_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase7_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase8_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL product_pipeline_phase9_1        : signed(33 DOWNTO 0); -- sfix34_En27
  SIGNAL sumvector1                       : sumdelay_pipeline_type(0 TO 6); -- sfix35_En27
  SIGNAL sumdelay_pipeline1               : sumdelay_pipeline_type(0 TO 6); -- sfix35_En27
  SIGNAL sumvector2                       : sumdelay_pipeline_type(0 TO 3); -- sfix35_En27
  SIGNAL add_temp                         : signed(35 DOWNTO 0); -- sfix36_En27
  SIGNAL add_temp_1                       : signed(35 DOWNTO 0); -- sfix36_En27
  SIGNAL add_temp_2                       : signed(35 DOWNTO 0); -- sfix36_En27
  SIGNAL sumdelay_pipeline2               : sumdelay_pipeline_type(0 TO 3); -- sfix35_En27
  SIGNAL sumvector3                       : sumdelay_pipeline_type(0 TO 1); -- sfix35_En27
  SIGNAL add_temp_3                       : signed(35 DOWNTO 0); -- sfix36_En27
  SIGNAL add_temp_4                       : signed(35 DOWNTO 0); -- sfix36_En27
  SIGNAL sumdelay_pipeline3               : sumdelay_pipeline_type(0 TO 1); -- sfix35_En27
  SIGNAL sum4                             : signed(34 DOWNTO 0); -- sfix35_En27
  SIGNAL add_temp_5                       : signed(35 DOWNTO 0); -- sfix36_En27
  SIGNAL output_typeconvert               : signed(34 DOWNTO 0); -- sfix35_En27
  SIGNAL ce_delayline1                    : std_logic; -- boolean
  SIGNAL ce_delayline2                    : std_logic; -- boolean
  SIGNAL ce_delayline3                    : std_logic; -- boolean
  SIGNAL ce_delayline4                    : std_logic; -- boolean
  SIGNAL ce_delayline5                    : std_logic; -- boolean
  SIGNAL ce_delayline6                    : std_logic; -- boolean
  SIGNAL ce_delayline7                    : std_logic; -- boolean
  SIGNAL ce_delayline8                    : std_logic; -- boolean
  SIGNAL ce_delayline9                    : std_logic; -- boolean
  SIGNAL ce_delayline10                   : std_logic; -- boolean
  SIGNAL ce_delayline11                   : std_logic; -- boolean
  SIGNAL ce_delayline12                   : std_logic; -- boolean
  SIGNAL ce_delayline13                   : std_logic; -- boolean
  SIGNAL ce_delayline14                   : std_logic; -- boolean
  SIGNAL ce_delayline15                   : std_logic; -- boolean
  SIGNAL ce_delayline16                   : std_logic; -- boolean
  SIGNAL ce_delayline17                   : std_logic; -- boolean
  SIGNAL ce_delayline18                   : std_logic; -- boolean
  SIGNAL ce_delayline19                   : std_logic; -- boolean
  SIGNAL ce_delayline20                   : std_logic; -- boolean
  SIGNAL ce_delayline21                   : std_logic; -- boolean
  SIGNAL ce_delayline22                   : std_logic; -- boolean
  SIGNAL ce_delayline23                   : std_logic; -- boolean
  SIGNAL ce_delayline24                   : std_logic; -- boolean
  SIGNAL ce_delayline25                   : std_logic; -- boolean
  SIGNAL ce_delayline26                   : std_logic; -- boolean
  SIGNAL ce_delayline27                   : std_logic; -- boolean
  SIGNAL ce_delayline28                   : std_logic; -- boolean
  SIGNAL ce_delayline29                   : std_logic; -- boolean
  SIGNAL ce_delayline30                   : std_logic; -- boolean
  SIGNAL ce_delayline31                   : std_logic; -- boolean
  SIGNAL ce_delayline32                   : std_logic; -- boolean
  SIGNAL ce_delayline33                   : std_logic; -- boolean
  SIGNAL ce_delayline34                   : std_logic; -- boolean
  SIGNAL ce_delayline35                   : std_logic; -- boolean
  SIGNAL ce_delayline36                   : std_logic; -- boolean
  SIGNAL ce_delayline37                   : std_logic; -- boolean
  SIGNAL ce_delayline38                   : std_logic; -- boolean
  SIGNAL ce_delayline39                   : std_logic; -- boolean
  SIGNAL ce_delayline40                   : std_logic; -- boolean
  SIGNAL ce_delayline41                   : std_logic; -- boolean
  SIGNAL ce_delayline42                   : std_logic; -- boolean
  SIGNAL ce_gated                         : std_logic; -- boolean
  SIGNAL output_register                  : signed(34 DOWNTO 0); -- sfix35_En27


BEGIN

  -- Block Statements
  ce_output : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ring_count <= to_unsigned(1, 10);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        ring_count <= ring_count(0) & ring_count(9 DOWNTO 1);
      END IF;
    END IF; 
  END PROCESS ce_output;

  phase_0 <= ring_count(0)  AND clk_enable;

  phase_1 <= ring_count(1)  AND clk_enable;

  phase_2 <= ring_count(2)  AND clk_enable;

  phase_3 <= ring_count(3)  AND clk_enable;

  phase_4 <= ring_count(4)  AND clk_enable;

  phase_5 <= ring_count(5)  AND clk_enable;

  phase_6 <= ring_count(6)  AND clk_enable;

  phase_7 <= ring_count(7)  AND clk_enable;

  phase_8 <= ring_count(8)  AND clk_enable;

  phase_9 <= ring_count(9)  AND clk_enable;

  --   ------------------ CE Output Register ------------------

  ce_output_register : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ce_out_reg <= '0';
    ELSIF clk'event AND clk = '1' THEN
      ce_out_reg <= phase_9;
      
    END IF; 
  END PROCESS ce_output_register;

  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  Delay_Pipeline_Phase0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase0 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_9 = '1' THEN
        input_pipeline_phase0 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase0_process;

  Delay_Pipeline_Phase1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase1(0 TO 1) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        input_pipeline_phase1(0) <= input_register;
        input_pipeline_phase1(1) <= input_pipeline_phase1(0);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase1_process;

  Delay_Pipeline_Phase2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase2(0 TO 1) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        input_pipeline_phase2(0) <= input_register;
        input_pipeline_phase2(1) <= input_pipeline_phase2(0);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase2_process;

  Delay_Pipeline_Phase3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_2 = '1' THEN
        input_pipeline_phase3 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase3_process;

  Delay_Pipeline_Phase4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase4 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_3 = '1' THEN
        input_pipeline_phase4 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase4_process;

  Delay_Pipeline_Phase5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase5 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_4 = '1' THEN
        input_pipeline_phase5 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase5_process;

  Delay_Pipeline_Phase6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase6 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_5 = '1' THEN
        input_pipeline_phase6 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase6_process;

  Delay_Pipeline_Phase7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase7 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_6 = '1' THEN
        input_pipeline_phase7 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase7_process;

  Delay_Pipeline_Phase8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase8 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_7 = '1' THEN
        input_pipeline_phase8 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase8_process;

  Delay_Pipeline_Phase9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_pipeline_phase9 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_8 = '1' THEN
        input_pipeline_phase9 <= input_register;
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_Phase9_process;

  tapsum1 <= resize(input_pipeline_phase1(0), 18) + resize(input_pipeline_phase1(1), 18);

  product_phase0_1 <= input_register * coeffphase1_1;

  product_phase0_2 <= input_pipeline_phase0 * coeffphase1_2;

  product_phase1_1 <= input_pipeline_phase1(0) * coeffphase2_1;

  product_phase1_2 <= input_pipeline_phase1(1) * coeffphase2_2;

  product_phase2_1 <= input_pipeline_phase2(0) * coeffphase3_1;

  product_phase2_2 <= input_pipeline_phase2(1) * coeffphase3_2;

  product_phase3_1 <= input_pipeline_phase3 * coeffphase4_1;

  product_phase4_1 <= input_pipeline_phase4 * coeffphase5_1;

  product_phase5_1 <= input_pipeline_phase5 * coeffphase6_1;

  product_phase6_1 <= input_pipeline_phase6 * coeffphase7_1;

  product_phase7_1 <= input_pipeline_phase7 * coeffphase8_1;

  product_phase8_1 <= input_pipeline_phase8 * coeffphase9_1;

  product_phase9_1 <= input_pipeline_phase9 * coeffphase10_1;

  product_pipeline_process9 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      product_pipeline_phase0_1 <= (OTHERS => '0');
      product_pipeline_phase1_1 <= (OTHERS => '0');
      product_pipeline_phase2_1 <= (OTHERS => '0');
      product_pipeline_phase3_1 <= (OTHERS => '0');
      product_pipeline_phase4_1 <= (OTHERS => '0');
      product_pipeline_phase5_1 <= (OTHERS => '0');
      product_pipeline_phase6_1 <= (OTHERS => '0');
      product_pipeline_phase7_1 <= (OTHERS => '0');
      product_pipeline_phase8_1 <= (OTHERS => '0');
      product_pipeline_phase9_1 <= (OTHERS => '0');
      product_pipeline_phase0_2 <= (OTHERS => '0');
      product_pipeline_phase1_2 <= (OTHERS => '0');
      product_pipeline_phase2_2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_9 = '1' THEN
        product_pipeline_phase0_1 <= product_phase0_1;
        product_pipeline_phase1_1 <= product_phase1_1;
        product_pipeline_phase2_1 <= product_phase2_1;
        product_pipeline_phase3_1 <= product_phase3_1;
        product_pipeline_phase4_1 <= product_phase4_1;
        product_pipeline_phase5_1 <= product_phase5_1;
        product_pipeline_phase6_1 <= product_phase6_1;
        product_pipeline_phase7_1 <= product_phase7_1;
        product_pipeline_phase8_1 <= product_phase8_1;
        product_pipeline_phase9_1 <= product_phase9_1;
        product_pipeline_phase0_2 <= product_phase0_2;
        product_pipeline_phase1_2 <= product_phase1_2;
        product_pipeline_phase2_2 <= product_phase2_2;
      END IF;
    END IF; 
  END PROCESS product_pipeline_process9;

  sumvector1(0) <= resize(product_pipeline_phase9_1, 35) + resize(product_pipeline_phase8_1, 35);

  sumvector1(1) <= resize(product_pipeline_phase7_1, 35) + resize(product_pipeline_phase6_1, 35);

  sumvector1(2) <= resize(product_pipeline_phase5_1, 35) + resize(product_pipeline_phase4_1, 35);

  sumvector1(3) <= resize(product_pipeline_phase3_1, 35) + resize(product_pipeline_phase2_1, 35);

  sumvector1(4) <= resize(product_pipeline_phase2_2, 35) + resize(product_pipeline_phase1_1, 35);

  sumvector1(5) <= resize(product_pipeline_phase1_2, 35) + resize(product_pipeline_phase0_1, 35);

  sumvector1(6) <= resize(product_pipeline_phase0_2, 35);

  sumdelay_pipeline_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumdelay_pipeline1 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_9 = '1' THEN
        sumdelay_pipeline1(0 TO 6) <= sumvector1(0 TO 6);
      END IF;
    END IF; 
  END PROCESS sumdelay_pipeline_process1;

  add_temp <= resize(sumdelay_pipeline1(0), 36) + resize(sumdelay_pipeline1(1), 36);
  sumvector2(0) <= add_temp(34 DOWNTO 0);

  add_temp_1 <= resize(sumdelay_pipeline1(2), 36) + resize(sumdelay_pipeline1(3), 36);
  sumvector2(1) <= add_temp_1(34 DOWNTO 0);

  add_temp_2 <= resize(sumdelay_pipeline1(4), 36) + resize(sumdelay_pipeline1(5), 36);
  sumvector2(2) <= add_temp_2(34 DOWNTO 0);

  sumvector2(3) <= sumdelay_pipeline1(6);

  sumdelay_pipeline_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumdelay_pipeline2 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_9 = '1' THEN
        sumdelay_pipeline2(0 TO 3) <= sumvector2(0 TO 3);
      END IF;
    END IF; 
  END PROCESS sumdelay_pipeline_process2;

  add_temp_3 <= resize(sumdelay_pipeline2(0), 36) + resize(sumdelay_pipeline2(1), 36);
  sumvector3(0) <= add_temp_3(34 DOWNTO 0);

  add_temp_4 <= resize(sumdelay_pipeline2(2), 36) + resize(sumdelay_pipeline2(3), 36);
  sumvector3(1) <= add_temp_4(34 DOWNTO 0);

  sumdelay_pipeline_process3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumdelay_pipeline3 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_9 = '1' THEN
        sumdelay_pipeline3(0 TO 1) <= sumvector3(0 TO 1);
      END IF;
    END IF; 
  END PROCESS sumdelay_pipeline_process3;

  add_temp_5 <= resize(sumdelay_pipeline3(0), 36) + resize(sumdelay_pipeline3(1), 36);
  sum4 <= add_temp_5(34 DOWNTO 0);

  output_typeconvert <= sum4;

  ce_delay : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ce_delayline1 <= '0';
      ce_delayline2 <= '0';
      ce_delayline3 <= '0';
      ce_delayline4 <= '0';
      ce_delayline5 <= '0';
      ce_delayline6 <= '0';
      ce_delayline7 <= '0';
      ce_delayline8 <= '0';
      ce_delayline9 <= '0';
      ce_delayline10 <= '0';
      ce_delayline11 <= '0';
      ce_delayline12 <= '0';
      ce_delayline13 <= '0';
      ce_delayline14 <= '0';
      ce_delayline15 <= '0';
      ce_delayline16 <= '0';
      ce_delayline17 <= '0';
      ce_delayline18 <= '0';
      ce_delayline19 <= '0';
      ce_delayline20 <= '0';
      ce_delayline21 <= '0';
      ce_delayline22 <= '0';
      ce_delayline23 <= '0';
      ce_delayline24 <= '0';
      ce_delayline25 <= '0';
      ce_delayline26 <= '0';
      ce_delayline27 <= '0';
      ce_delayline28 <= '0';
      ce_delayline29 <= '0';
      ce_delayline30 <= '0';
      ce_delayline31 <= '0';
      ce_delayline32 <= '0';
      ce_delayline33 <= '0';
      ce_delayline34 <= '0';
      ce_delayline35 <= '0';
      ce_delayline36 <= '0';
      ce_delayline37 <= '0';
      ce_delayline38 <= '0';
      ce_delayline39 <= '0';
      ce_delayline40 <= '0';
      ce_delayline41 <= '0';
      ce_delayline42 <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        ce_delayline1 <= clk_enable;
        ce_delayline2 <= ce_delayline1;
        ce_delayline3 <= ce_delayline2;
        ce_delayline4 <= ce_delayline3;
        ce_delayline5 <= ce_delayline4;
        ce_delayline6 <= ce_delayline5;
        ce_delayline7 <= ce_delayline6;
        ce_delayline8 <= ce_delayline7;
        ce_delayline9 <= ce_delayline8;
        ce_delayline10 <= ce_delayline9;
        ce_delayline11 <= ce_delayline10;
        ce_delayline12 <= ce_delayline11;
        ce_delayline13 <= ce_delayline12;
        ce_delayline14 <= ce_delayline13;
        ce_delayline15 <= ce_delayline14;
        ce_delayline16 <= ce_delayline15;
        ce_delayline17 <= ce_delayline16;
        ce_delayline18 <= ce_delayline17;
        ce_delayline19 <= ce_delayline18;
        ce_delayline20 <= ce_delayline19;
        ce_delayline21 <= ce_delayline20;
        ce_delayline22 <= ce_delayline21;
        ce_delayline23 <= ce_delayline22;
        ce_delayline24 <= ce_delayline23;
        ce_delayline25 <= ce_delayline24;
        ce_delayline26 <= ce_delayline25;
        ce_delayline27 <= ce_delayline26;
        ce_delayline28 <= ce_delayline27;
        ce_delayline29 <= ce_delayline28;
        ce_delayline30 <= ce_delayline29;
        ce_delayline31 <= ce_delayline30;
        ce_delayline32 <= ce_delayline31;
        ce_delayline33 <= ce_delayline32;
        ce_delayline34 <= ce_delayline33;
        ce_delayline35 <= ce_delayline34;
        ce_delayline36 <= ce_delayline35;
        ce_delayline37 <= ce_delayline36;
        ce_delayline38 <= ce_delayline37;
        ce_delayline39 <= ce_delayline38;
        ce_delayline40 <= ce_delayline39;
        ce_delayline41 <= ce_delayline40;
        ce_delayline42 <= ce_delayline41;
      END IF;
    END IF; 
  END PROCESS ce_delay;

  ce_gated <=  ce_delayline42 AND ce_out_reg;

  output_register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_9 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS output_register_process;

  -- Assignment Statements
  ce_out <= ce_gated;
  filter_out <= std_logic_vector(output_register);
END rtl;
