-- -------------------------------------------------------------
--
-- Module: Data_Filter
-- Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
-- Generated on: 2022-08-06 14:34:20
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: C:\Users\Elia Yfrach\Desktop\Project\FM\Filters
-- Name: Data_Filter
-- TestBenchName: Data_Filter_tb
-- TestBenchStimulus: impulse step ramp chirp noise 
-- GenerateHDLTestBench: off

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 113
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,21 -> [-1.562500e-02 1.562500e-02)
-- Input             : s17,0 -> [-65536 65536)
-- Filter Internals  : Full Precision
--   Output          : s38,21 -> [-65536 65536)  (auto determined)
--   Product         : s32,21 -> [-1024 1024)  (auto determined)
--   Accumulator     : s38,21 -> [-65536 65536)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY Data_Filter_stage1 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable_stage1               :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in_stage1                :   IN    std_logic_vector(16 DOWNTO 0); -- sfix17
         filter_out_stage1               :   OUT   std_logic_vector(37 DOWNTO 0)  -- sfix38_En21
         );

END Data_Filter_stage1;


----------------------------------------------------------------
--Module Architecture: Data_Filter_stage1
----------------------------------------------------------------
ARCHITECTURE rtl OF Data_Filter_stage1 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(16 DOWNTO 0); -- sfix17
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(11818, 16); -- sfix16_En21
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(2935, 16); -- sfix16_En21
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(3287, 16); -- sfix16_En21
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(3663, 16); -- sfix16_En21
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(4058, 16); -- sfix16_En21
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(4477, 16); -- sfix16_En21
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(4914, 16); -- sfix16_En21
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(5374, 16); -- sfix16_En21
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(5852, 16); -- sfix16_En21
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(6353, 16); -- sfix16_En21
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(6872, 16); -- sfix16_En21
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(7412, 16); -- sfix16_En21
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(7968, 16); -- sfix16_En21
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(8544, 16); -- sfix16_En21
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(9135, 16); -- sfix16_En21
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(9745, 16); -- sfix16_En21
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(10367, 16); -- sfix16_En21
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(11007, 16); -- sfix16_En21
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(11657, 16); -- sfix16_En21
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(12321, 16); -- sfix16_En21
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(12993, 16); -- sfix16_En21
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(13677, 16); -- sfix16_En21
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(14367, 16); -- sfix16_En21
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(15064, 16); -- sfix16_En21
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(15763, 16); -- sfix16_En21
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(16468, 16); -- sfix16_En21
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(17177, 16); -- sfix16_En21
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(17872, 16); -- sfix16_En21
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(18592, 16); -- sfix16_En21
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(19288, 16); -- sfix16_En21
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(19975, 16); -- sfix16_En21
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(20666, 16); -- sfix16_En21
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(21349, 16); -- sfix16_En21
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(22020, 16); -- sfix16_En21
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(22672, 16); -- sfix16_En21
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(23312, 16); -- sfix16_En21
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(23934, 16); -- sfix16_En21
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(24543, 16); -- sfix16_En21
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(25131, 16); -- sfix16_En21
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(25700, 16); -- sfix16_En21
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(26243, 16); -- sfix16_En21
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(26762, 16); -- sfix16_En21
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(27252, 16); -- sfix16_En21
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(27718, 16); -- sfix16_En21
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(28153, 16); -- sfix16_En21
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(28562, 16); -- sfix16_En21
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(28937, 16); -- sfix16_En21
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(29283, 16); -- sfix16_En21
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(29593, 16); -- sfix16_En21
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(29872, 16); -- sfix16_En21
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(30113, 16); -- sfix16_En21
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(30319, 16); -- sfix16_En21
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(30485, 16); -- sfix16_En21
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(30614, 16); -- sfix16_En21
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(30709, 16); -- sfix16_En21
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(30764, 16); -- sfix16_En21
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(30783, 16); -- sfix16_En21
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(30764, 16); -- sfix16_En21
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(30709, 16); -- sfix16_En21
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(30614, 16); -- sfix16_En21
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(30485, 16); -- sfix16_En21
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(30319, 16); -- sfix16_En21
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(30113, 16); -- sfix16_En21
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(29872, 16); -- sfix16_En21
  CONSTANT coeff65                        : signed(15 DOWNTO 0) := to_signed(29593, 16); -- sfix16_En21
  CONSTANT coeff66                        : signed(15 DOWNTO 0) := to_signed(29283, 16); -- sfix16_En21
  CONSTANT coeff67                        : signed(15 DOWNTO 0) := to_signed(28937, 16); -- sfix16_En21
  CONSTANT coeff68                        : signed(15 DOWNTO 0) := to_signed(28562, 16); -- sfix16_En21
  CONSTANT coeff69                        : signed(15 DOWNTO 0) := to_signed(28153, 16); -- sfix16_En21
  CONSTANT coeff70                        : signed(15 DOWNTO 0) := to_signed(27718, 16); -- sfix16_En21
  CONSTANT coeff71                        : signed(15 DOWNTO 0) := to_signed(27252, 16); -- sfix16_En21
  CONSTANT coeff72                        : signed(15 DOWNTO 0) := to_signed(26762, 16); -- sfix16_En21
  CONSTANT coeff73                        : signed(15 DOWNTO 0) := to_signed(26243, 16); -- sfix16_En21
  CONSTANT coeff74                        : signed(15 DOWNTO 0) := to_signed(25700, 16); -- sfix16_En21
  CONSTANT coeff75                        : signed(15 DOWNTO 0) := to_signed(25131, 16); -- sfix16_En21
  CONSTANT coeff76                        : signed(15 DOWNTO 0) := to_signed(24543, 16); -- sfix16_En21
  CONSTANT coeff77                        : signed(15 DOWNTO 0) := to_signed(23934, 16); -- sfix16_En21
  CONSTANT coeff78                        : signed(15 DOWNTO 0) := to_signed(23312, 16); -- sfix16_En21
  CONSTANT coeff79                        : signed(15 DOWNTO 0) := to_signed(22672, 16); -- sfix16_En21
  CONSTANT coeff80                        : signed(15 DOWNTO 0) := to_signed(22020, 16); -- sfix16_En21
  CONSTANT coeff81                        : signed(15 DOWNTO 0) := to_signed(21349, 16); -- sfix16_En21
  CONSTANT coeff82                        : signed(15 DOWNTO 0) := to_signed(20666, 16); -- sfix16_En21
  CONSTANT coeff83                        : signed(15 DOWNTO 0) := to_signed(19975, 16); -- sfix16_En21
  CONSTANT coeff84                        : signed(15 DOWNTO 0) := to_signed(19288, 16); -- sfix16_En21
  CONSTANT coeff85                        : signed(15 DOWNTO 0) := to_signed(18592, 16); -- sfix16_En21
  CONSTANT coeff86                        : signed(15 DOWNTO 0) := to_signed(17872, 16); -- sfix16_En21
  CONSTANT coeff87                        : signed(15 DOWNTO 0) := to_signed(17177, 16); -- sfix16_En21
  CONSTANT coeff88                        : signed(15 DOWNTO 0) := to_signed(16468, 16); -- sfix16_En21
  CONSTANT coeff89                        : signed(15 DOWNTO 0) := to_signed(15763, 16); -- sfix16_En21
  CONSTANT coeff90                        : signed(15 DOWNTO 0) := to_signed(15064, 16); -- sfix16_En21
  CONSTANT coeff91                        : signed(15 DOWNTO 0) := to_signed(14367, 16); -- sfix16_En21
  CONSTANT coeff92                        : signed(15 DOWNTO 0) := to_signed(13677, 16); -- sfix16_En21
  CONSTANT coeff93                        : signed(15 DOWNTO 0) := to_signed(12993, 16); -- sfix16_En21
  CONSTANT coeff94                        : signed(15 DOWNTO 0) := to_signed(12321, 16); -- sfix16_En21
  CONSTANT coeff95                        : signed(15 DOWNTO 0) := to_signed(11657, 16); -- sfix16_En21
  CONSTANT coeff96                        : signed(15 DOWNTO 0) := to_signed(11007, 16); -- sfix16_En21
  CONSTANT coeff97                        : signed(15 DOWNTO 0) := to_signed(10367, 16); -- sfix16_En21
  CONSTANT coeff98                        : signed(15 DOWNTO 0) := to_signed(9745, 16); -- sfix16_En21
  CONSTANT coeff99                        : signed(15 DOWNTO 0) := to_signed(9135, 16); -- sfix16_En21
  CONSTANT coeff100                       : signed(15 DOWNTO 0) := to_signed(8544, 16); -- sfix16_En21
  CONSTANT coeff101                       : signed(15 DOWNTO 0) := to_signed(7968, 16); -- sfix16_En21
  CONSTANT coeff102                       : signed(15 DOWNTO 0) := to_signed(7412, 16); -- sfix16_En21
  CONSTANT coeff103                       : signed(15 DOWNTO 0) := to_signed(6872, 16); -- sfix16_En21
  CONSTANT coeff104                       : signed(15 DOWNTO 0) := to_signed(6353, 16); -- sfix16_En21
  CONSTANT coeff105                       : signed(15 DOWNTO 0) := to_signed(5852, 16); -- sfix16_En21
  CONSTANT coeff106                       : signed(15 DOWNTO 0) := to_signed(5374, 16); -- sfix16_En21
  CONSTANT coeff107                       : signed(15 DOWNTO 0) := to_signed(4914, 16); -- sfix16_En21
  CONSTANT coeff108                       : signed(15 DOWNTO 0) := to_signed(4477, 16); -- sfix16_En21
  CONSTANT coeff109                       : signed(15 DOWNTO 0) := to_signed(4058, 16); -- sfix16_En21
  CONSTANT coeff110                       : signed(15 DOWNTO 0) := to_signed(3663, 16); -- sfix16_En21
  CONSTANT coeff111                       : signed(15 DOWNTO 0) := to_signed(3287, 16); -- sfix16_En21
  CONSTANT coeff112                       : signed(15 DOWNTO 0) := to_signed(2935, 16); -- sfix16_En21
  CONSTANT coeff113                       : signed(15 DOWNTO 0) := to_signed(11818, 16); -- sfix16_En21

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 112); -- sfix17
  SIGNAL product113                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp                         : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product112                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_1                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product111                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_2                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product110                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_3                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product109                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_4                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product108                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_5                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product107                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_6                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product106                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_7                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product105                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_8                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product104                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_9                       : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product103                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_10                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product102                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_11                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product101                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_12                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product100                       : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_13                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product99                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_14                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product98                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_15                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product97                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_16                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product96                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_17                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product95                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_18                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product94                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_19                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product93                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_20                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product92                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_21                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product91                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_22                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product90                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_23                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product89                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_24                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product88                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_25                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product87                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_26                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product86                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_27                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product85                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_28                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product84                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_29                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product83                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_30                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product82                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_31                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product81                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_32                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product80                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_33                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product79                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_34                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product78                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_35                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product77                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_36                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product76                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_37                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product75                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_38                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product74                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_39                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product73                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_40                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product72                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_41                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product71                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_42                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product70                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_43                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product69                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_44                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product68                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_45                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product67                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_46                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product66                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_47                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product65                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_48                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product64                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_49                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product63                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_50                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product62                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_51                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product61                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_52                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product60                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_53                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product59                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_54                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product58                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_55                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product57                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_56                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product56                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_57                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product55                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_58                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product54                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_59                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product53                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_60                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product52                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_61                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product51                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_62                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product50                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_63                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product49                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_64                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product48                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_65                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product47                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_66                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product46                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_67                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product45                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_68                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product44                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_69                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product43                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_70                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product42                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_71                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product41                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_72                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product40                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_73                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product39                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_74                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product38                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_75                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product37                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_76                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product36                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_77                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product35                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_78                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product34                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_79                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product33                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_80                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product32                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_81                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product31                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_82                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product30                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_83                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product29                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_84                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product28                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_85                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product27                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_86                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product26                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_87                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product25                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_88                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product24                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_89                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product23                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_90                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product22                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_91                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product21                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_92                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product20                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_93                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product19                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_94                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product18                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_95                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product17                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_96                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product16                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_97                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product15                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_98                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product14                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_99                      : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product13                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_100                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product12                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_101                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product11                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_102                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product10                        : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_103                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product9                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_104                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product8                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_105                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product7                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_106                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product6                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_107                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product5                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_108                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product4                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_109                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product3                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_110                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product2                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_111                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL product1_cast                    : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL product1                         : signed(31 DOWNTO 0); -- sfix32_En21
  SIGNAL mul_temp_112                     : signed(32 DOWNTO 0); -- sfix33_En21
  SIGNAL sum1                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp                         : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum2                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_1                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum3                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_2                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum4                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_3                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum5                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_4                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum6                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_5                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum7                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_6                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum8                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_7                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum9                             : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_8                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum10                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_9                       : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum11                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_10                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum12                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_11                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum13                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_12                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum14                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_13                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum15                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_14                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum16                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_15                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum17                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_16                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum18                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_17                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum19                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_18                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum20                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_19                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum21                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_20                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum22                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_21                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum23                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_22                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum24                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_23                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum25                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_24                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum26                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_25                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum27                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_26                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum28                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_27                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum29                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_28                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum30                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_29                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum31                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_30                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum32                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_31                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum33                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_32                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum34                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_33                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum35                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_34                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum36                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_35                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum37                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_36                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum38                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_37                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum39                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_38                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum40                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_39                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum41                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_40                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum42                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_41                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum43                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_42                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum44                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_43                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum45                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_44                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum46                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_45                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum47                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_46                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum48                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_47                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum49                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_48                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum50                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_49                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum51                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_50                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum52                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_51                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum53                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_52                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum54                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_53                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum55                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_54                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum56                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_55                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum57                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_56                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum58                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_57                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum59                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_58                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum60                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_59                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum61                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_60                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum62                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_61                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum63                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_62                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum64                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_63                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum65                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_64                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum66                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_65                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum67                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_66                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum68                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_67                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum69                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_68                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum70                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_69                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum71                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_70                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum72                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_71                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum73                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_72                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum74                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_73                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum75                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_74                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum76                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_75                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum77                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_76                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum78                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_77                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum79                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_78                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum80                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_79                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum81                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_80                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum82                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_81                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum83                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_82                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum84                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_83                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum85                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_84                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum86                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_85                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum87                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_86                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum88                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_87                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum89                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_88                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum90                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_89                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum91                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_90                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum92                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_91                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum93                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_92                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum94                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_93                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum95                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_94                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum96                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_95                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum97                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_96                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum98                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_97                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum99                            : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_98                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum100                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_99                      : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum101                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_100                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum102                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_101                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum103                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_102                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum104                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_103                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum105                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_104                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum106                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_105                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum107                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_106                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum108                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_107                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum109                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_108                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum110                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_109                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum111                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_110                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL sum112                           : signed(37 DOWNTO 0); -- sfix38_En21
  SIGNAL add_temp_111                     : signed(38 DOWNTO 0); -- sfix39_En21
  SIGNAL output_typeconvert               : signed(37 DOWNTO 0); -- sfix38_En21


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 112) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable_stage1 = '1' THEN
        delay_pipeline(0) <= signed(filter_in_stage1);
        delay_pipeline(1 TO 112) <= delay_pipeline(0 TO 111);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(112) * coeff113;
  product113 <= mul_temp(31 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(111) * coeff112;
  product112 <= mul_temp_1(31 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(110) * coeff111;
  product111 <= mul_temp_2(31 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(109) * coeff110;
  product110 <= mul_temp_3(31 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(108) * coeff109;
  product109 <= mul_temp_4(31 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(107) * coeff108;
  product108 <= mul_temp_5(31 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(106) * coeff107;
  product107 <= mul_temp_6(31 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(105) * coeff106;
  product106 <= mul_temp_7(31 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(104) * coeff105;
  product105 <= mul_temp_8(31 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(103) * coeff104;
  product104 <= mul_temp_9(31 DOWNTO 0);

  mul_temp_10 <= delay_pipeline(102) * coeff103;
  product103 <= mul_temp_10(31 DOWNTO 0);

  mul_temp_11 <= delay_pipeline(101) * coeff102;
  product102 <= mul_temp_11(31 DOWNTO 0);

  mul_temp_12 <= delay_pipeline(100) * coeff101;
  product101 <= mul_temp_12(31 DOWNTO 0);

  mul_temp_13 <= delay_pipeline(99) * coeff100;
  product100 <= mul_temp_13(31 DOWNTO 0);

  mul_temp_14 <= delay_pipeline(98) * coeff99;
  product99 <= mul_temp_14(31 DOWNTO 0);

  mul_temp_15 <= delay_pipeline(97) * coeff98;
  product98 <= mul_temp_15(31 DOWNTO 0);

  mul_temp_16 <= delay_pipeline(96) * coeff97;
  product97 <= mul_temp_16(31 DOWNTO 0);

  mul_temp_17 <= delay_pipeline(95) * coeff96;
  product96 <= mul_temp_17(31 DOWNTO 0);

  mul_temp_18 <= delay_pipeline(94) * coeff95;
  product95 <= mul_temp_18(31 DOWNTO 0);

  mul_temp_19 <= delay_pipeline(93) * coeff94;
  product94 <= mul_temp_19(31 DOWNTO 0);

  mul_temp_20 <= delay_pipeline(92) * coeff93;
  product93 <= mul_temp_20(31 DOWNTO 0);

  mul_temp_21 <= delay_pipeline(91) * coeff92;
  product92 <= mul_temp_21(31 DOWNTO 0);

  mul_temp_22 <= delay_pipeline(90) * coeff91;
  product91 <= mul_temp_22(31 DOWNTO 0);

  mul_temp_23 <= delay_pipeline(89) * coeff90;
  product90 <= mul_temp_23(31 DOWNTO 0);

  mul_temp_24 <= delay_pipeline(88) * coeff89;
  product89 <= mul_temp_24(31 DOWNTO 0);

  mul_temp_25 <= delay_pipeline(87) * coeff88;
  product88 <= mul_temp_25(31 DOWNTO 0);

  mul_temp_26 <= delay_pipeline(86) * coeff87;
  product87 <= mul_temp_26(31 DOWNTO 0);

  mul_temp_27 <= delay_pipeline(85) * coeff86;
  product86 <= mul_temp_27(31 DOWNTO 0);

  mul_temp_28 <= delay_pipeline(84) * coeff85;
  product85 <= mul_temp_28(31 DOWNTO 0);

  mul_temp_29 <= delay_pipeline(83) * coeff84;
  product84 <= mul_temp_29(31 DOWNTO 0);

  mul_temp_30 <= delay_pipeline(82) * coeff83;
  product83 <= mul_temp_30(31 DOWNTO 0);

  mul_temp_31 <= delay_pipeline(81) * coeff82;
  product82 <= mul_temp_31(31 DOWNTO 0);

  mul_temp_32 <= delay_pipeline(80) * coeff81;
  product81 <= mul_temp_32(31 DOWNTO 0);

  mul_temp_33 <= delay_pipeline(79) * coeff80;
  product80 <= mul_temp_33(31 DOWNTO 0);

  mul_temp_34 <= delay_pipeline(78) * coeff79;
  product79 <= mul_temp_34(31 DOWNTO 0);

  mul_temp_35 <= delay_pipeline(77) * coeff78;
  product78 <= mul_temp_35(31 DOWNTO 0);

  mul_temp_36 <= delay_pipeline(76) * coeff77;
  product77 <= mul_temp_36(31 DOWNTO 0);

  mul_temp_37 <= delay_pipeline(75) * coeff76;
  product76 <= mul_temp_37(31 DOWNTO 0);

  mul_temp_38 <= delay_pipeline(74) * coeff75;
  product75 <= mul_temp_38(31 DOWNTO 0);

  mul_temp_39 <= delay_pipeline(73) * coeff74;
  product74 <= mul_temp_39(31 DOWNTO 0);

  mul_temp_40 <= delay_pipeline(72) * coeff73;
  product73 <= mul_temp_40(31 DOWNTO 0);

  mul_temp_41 <= delay_pipeline(71) * coeff72;
  product72 <= mul_temp_41(31 DOWNTO 0);

  mul_temp_42 <= delay_pipeline(70) * coeff71;
  product71 <= mul_temp_42(31 DOWNTO 0);

  mul_temp_43 <= delay_pipeline(69) * coeff70;
  product70 <= mul_temp_43(31 DOWNTO 0);

  mul_temp_44 <= delay_pipeline(68) * coeff69;
  product69 <= mul_temp_44(31 DOWNTO 0);

  mul_temp_45 <= delay_pipeline(67) * coeff68;
  product68 <= mul_temp_45(31 DOWNTO 0);

  mul_temp_46 <= delay_pipeline(66) * coeff67;
  product67 <= mul_temp_46(31 DOWNTO 0);

  mul_temp_47 <= delay_pipeline(65) * coeff66;
  product66 <= mul_temp_47(31 DOWNTO 0);

  mul_temp_48 <= delay_pipeline(64) * coeff65;
  product65 <= mul_temp_48(31 DOWNTO 0);

  mul_temp_49 <= delay_pipeline(63) * coeff64;
  product64 <= mul_temp_49(31 DOWNTO 0);

  mul_temp_50 <= delay_pipeline(62) * coeff63;
  product63 <= mul_temp_50(31 DOWNTO 0);

  mul_temp_51 <= delay_pipeline(61) * coeff62;
  product62 <= mul_temp_51(31 DOWNTO 0);

  mul_temp_52 <= delay_pipeline(60) * coeff61;
  product61 <= mul_temp_52(31 DOWNTO 0);

  mul_temp_53 <= delay_pipeline(59) * coeff60;
  product60 <= mul_temp_53(31 DOWNTO 0);

  mul_temp_54 <= delay_pipeline(58) * coeff59;
  product59 <= mul_temp_54(31 DOWNTO 0);

  mul_temp_55 <= delay_pipeline(57) * coeff58;
  product58 <= mul_temp_55(31 DOWNTO 0);

  mul_temp_56 <= delay_pipeline(56) * coeff57;
  product57 <= mul_temp_56(31 DOWNTO 0);

  mul_temp_57 <= delay_pipeline(55) * coeff56;
  product56 <= mul_temp_57(31 DOWNTO 0);

  mul_temp_58 <= delay_pipeline(54) * coeff55;
  product55 <= mul_temp_58(31 DOWNTO 0);

  mul_temp_59 <= delay_pipeline(53) * coeff54;
  product54 <= mul_temp_59(31 DOWNTO 0);

  mul_temp_60 <= delay_pipeline(52) * coeff53;
  product53 <= mul_temp_60(31 DOWNTO 0);

  mul_temp_61 <= delay_pipeline(51) * coeff52;
  product52 <= mul_temp_61(31 DOWNTO 0);

  mul_temp_62 <= delay_pipeline(50) * coeff51;
  product51 <= mul_temp_62(31 DOWNTO 0);

  mul_temp_63 <= delay_pipeline(49) * coeff50;
  product50 <= mul_temp_63(31 DOWNTO 0);

  mul_temp_64 <= delay_pipeline(48) * coeff49;
  product49 <= mul_temp_64(31 DOWNTO 0);

  mul_temp_65 <= delay_pipeline(47) * coeff48;
  product48 <= mul_temp_65(31 DOWNTO 0);

  mul_temp_66 <= delay_pipeline(46) * coeff47;
  product47 <= mul_temp_66(31 DOWNTO 0);

  mul_temp_67 <= delay_pipeline(45) * coeff46;
  product46 <= mul_temp_67(31 DOWNTO 0);

  mul_temp_68 <= delay_pipeline(44) * coeff45;
  product45 <= mul_temp_68(31 DOWNTO 0);

  mul_temp_69 <= delay_pipeline(43) * coeff44;
  product44 <= mul_temp_69(31 DOWNTO 0);

  mul_temp_70 <= delay_pipeline(42) * coeff43;
  product43 <= mul_temp_70(31 DOWNTO 0);

  mul_temp_71 <= delay_pipeline(41) * coeff42;
  product42 <= mul_temp_71(31 DOWNTO 0);

  mul_temp_72 <= delay_pipeline(40) * coeff41;
  product41 <= mul_temp_72(31 DOWNTO 0);

  mul_temp_73 <= delay_pipeline(39) * coeff40;
  product40 <= mul_temp_73(31 DOWNTO 0);

  mul_temp_74 <= delay_pipeline(38) * coeff39;
  product39 <= mul_temp_74(31 DOWNTO 0);

  mul_temp_75 <= delay_pipeline(37) * coeff38;
  product38 <= mul_temp_75(31 DOWNTO 0);

  mul_temp_76 <= delay_pipeline(36) * coeff37;
  product37 <= mul_temp_76(31 DOWNTO 0);

  mul_temp_77 <= delay_pipeline(35) * coeff36;
  product36 <= mul_temp_77(31 DOWNTO 0);

  mul_temp_78 <= delay_pipeline(34) * coeff35;
  product35 <= mul_temp_78(31 DOWNTO 0);

  mul_temp_79 <= delay_pipeline(33) * coeff34;
  product34 <= mul_temp_79(31 DOWNTO 0);

  mul_temp_80 <= delay_pipeline(32) * coeff33;
  product33 <= mul_temp_80(31 DOWNTO 0);

  mul_temp_81 <= delay_pipeline(31) * coeff32;
  product32 <= mul_temp_81(31 DOWNTO 0);

  mul_temp_82 <= delay_pipeline(30) * coeff31;
  product31 <= mul_temp_82(31 DOWNTO 0);

  mul_temp_83 <= delay_pipeline(29) * coeff30;
  product30 <= mul_temp_83(31 DOWNTO 0);

  mul_temp_84 <= delay_pipeline(28) * coeff29;
  product29 <= mul_temp_84(31 DOWNTO 0);

  mul_temp_85 <= delay_pipeline(27) * coeff28;
  product28 <= mul_temp_85(31 DOWNTO 0);

  mul_temp_86 <= delay_pipeline(26) * coeff27;
  product27 <= mul_temp_86(31 DOWNTO 0);

  mul_temp_87 <= delay_pipeline(25) * coeff26;
  product26 <= mul_temp_87(31 DOWNTO 0);

  mul_temp_88 <= delay_pipeline(24) * coeff25;
  product25 <= mul_temp_88(31 DOWNTO 0);

  mul_temp_89 <= delay_pipeline(23) * coeff24;
  product24 <= mul_temp_89(31 DOWNTO 0);

  mul_temp_90 <= delay_pipeline(22) * coeff23;
  product23 <= mul_temp_90(31 DOWNTO 0);

  mul_temp_91 <= delay_pipeline(21) * coeff22;
  product22 <= mul_temp_91(31 DOWNTO 0);

  mul_temp_92 <= delay_pipeline(20) * coeff21;
  product21 <= mul_temp_92(31 DOWNTO 0);

  mul_temp_93 <= delay_pipeline(19) * coeff20;
  product20 <= mul_temp_93(31 DOWNTO 0);

  mul_temp_94 <= delay_pipeline(18) * coeff19;
  product19 <= mul_temp_94(31 DOWNTO 0);

  mul_temp_95 <= delay_pipeline(17) * coeff18;
  product18 <= mul_temp_95(31 DOWNTO 0);

  mul_temp_96 <= delay_pipeline(16) * coeff17;
  product17 <= mul_temp_96(31 DOWNTO 0);

  mul_temp_97 <= delay_pipeline(15) * coeff16;
  product16 <= mul_temp_97(31 DOWNTO 0);

  mul_temp_98 <= delay_pipeline(14) * coeff15;
  product15 <= mul_temp_98(31 DOWNTO 0);

  mul_temp_99 <= delay_pipeline(13) * coeff14;
  product14 <= mul_temp_99(31 DOWNTO 0);

  mul_temp_100 <= delay_pipeline(12) * coeff13;
  product13 <= mul_temp_100(31 DOWNTO 0);

  mul_temp_101 <= delay_pipeline(11) * coeff12;
  product12 <= mul_temp_101(31 DOWNTO 0);

  mul_temp_102 <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp_102(31 DOWNTO 0);

  mul_temp_103 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_103(31 DOWNTO 0);

  mul_temp_104 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_104(31 DOWNTO 0);

  mul_temp_105 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_105(31 DOWNTO 0);

  mul_temp_106 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_106(31 DOWNTO 0);

  mul_temp_107 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_107(31 DOWNTO 0);

  mul_temp_108 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_108(31 DOWNTO 0);

  mul_temp_109 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_109(31 DOWNTO 0);

  mul_temp_110 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_110(31 DOWNTO 0);

  mul_temp_111 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_111(31 DOWNTO 0);

  product1_cast <= resize(product1, 38);

  mul_temp_112 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_112(31 DOWNTO 0);

  add_temp <= resize(product1_cast, 39) + resize(product2, 39);
  sum1 <= add_temp(37 DOWNTO 0);

  add_temp_1 <= resize(sum1, 39) + resize(product3, 39);
  sum2 <= add_temp_1(37 DOWNTO 0);

  add_temp_2 <= resize(sum2, 39) + resize(product4, 39);
  sum3 <= add_temp_2(37 DOWNTO 0);

  add_temp_3 <= resize(sum3, 39) + resize(product5, 39);
  sum4 <= add_temp_3(37 DOWNTO 0);

  add_temp_4 <= resize(sum4, 39) + resize(product6, 39);
  sum5 <= add_temp_4(37 DOWNTO 0);

  add_temp_5 <= resize(sum5, 39) + resize(product7, 39);
  sum6 <= add_temp_5(37 DOWNTO 0);

  add_temp_6 <= resize(sum6, 39) + resize(product8, 39);
  sum7 <= add_temp_6(37 DOWNTO 0);

  add_temp_7 <= resize(sum7, 39) + resize(product9, 39);
  sum8 <= add_temp_7(37 DOWNTO 0);

  add_temp_8 <= resize(sum8, 39) + resize(product10, 39);
  sum9 <= add_temp_8(37 DOWNTO 0);

  add_temp_9 <= resize(sum9, 39) + resize(product11, 39);
  sum10 <= add_temp_9(37 DOWNTO 0);

  add_temp_10 <= resize(sum10, 39) + resize(product12, 39);
  sum11 <= add_temp_10(37 DOWNTO 0);

  add_temp_11 <= resize(sum11, 39) + resize(product13, 39);
  sum12 <= add_temp_11(37 DOWNTO 0);

  add_temp_12 <= resize(sum12, 39) + resize(product14, 39);
  sum13 <= add_temp_12(37 DOWNTO 0);

  add_temp_13 <= resize(sum13, 39) + resize(product15, 39);
  sum14 <= add_temp_13(37 DOWNTO 0);

  add_temp_14 <= resize(sum14, 39) + resize(product16, 39);
  sum15 <= add_temp_14(37 DOWNTO 0);

  add_temp_15 <= resize(sum15, 39) + resize(product17, 39);
  sum16 <= add_temp_15(37 DOWNTO 0);

  add_temp_16 <= resize(sum16, 39) + resize(product18, 39);
  sum17 <= add_temp_16(37 DOWNTO 0);

  add_temp_17 <= resize(sum17, 39) + resize(product19, 39);
  sum18 <= add_temp_17(37 DOWNTO 0);

  add_temp_18 <= resize(sum18, 39) + resize(product20, 39);
  sum19 <= add_temp_18(37 DOWNTO 0);

  add_temp_19 <= resize(sum19, 39) + resize(product21, 39);
  sum20 <= add_temp_19(37 DOWNTO 0);

  add_temp_20 <= resize(sum20, 39) + resize(product22, 39);
  sum21 <= add_temp_20(37 DOWNTO 0);

  add_temp_21 <= resize(sum21, 39) + resize(product23, 39);
  sum22 <= add_temp_21(37 DOWNTO 0);

  add_temp_22 <= resize(sum22, 39) + resize(product24, 39);
  sum23 <= add_temp_22(37 DOWNTO 0);

  add_temp_23 <= resize(sum23, 39) + resize(product25, 39);
  sum24 <= add_temp_23(37 DOWNTO 0);

  add_temp_24 <= resize(sum24, 39) + resize(product26, 39);
  sum25 <= add_temp_24(37 DOWNTO 0);

  add_temp_25 <= resize(sum25, 39) + resize(product27, 39);
  sum26 <= add_temp_25(37 DOWNTO 0);

  add_temp_26 <= resize(sum26, 39) + resize(product28, 39);
  sum27 <= add_temp_26(37 DOWNTO 0);

  add_temp_27 <= resize(sum27, 39) + resize(product29, 39);
  sum28 <= add_temp_27(37 DOWNTO 0);

  add_temp_28 <= resize(sum28, 39) + resize(product30, 39);
  sum29 <= add_temp_28(37 DOWNTO 0);

  add_temp_29 <= resize(sum29, 39) + resize(product31, 39);
  sum30 <= add_temp_29(37 DOWNTO 0);

  add_temp_30 <= resize(sum30, 39) + resize(product32, 39);
  sum31 <= add_temp_30(37 DOWNTO 0);

  add_temp_31 <= resize(sum31, 39) + resize(product33, 39);
  sum32 <= add_temp_31(37 DOWNTO 0);

  add_temp_32 <= resize(sum32, 39) + resize(product34, 39);
  sum33 <= add_temp_32(37 DOWNTO 0);

  add_temp_33 <= resize(sum33, 39) + resize(product35, 39);
  sum34 <= add_temp_33(37 DOWNTO 0);

  add_temp_34 <= resize(sum34, 39) + resize(product36, 39);
  sum35 <= add_temp_34(37 DOWNTO 0);

  add_temp_35 <= resize(sum35, 39) + resize(product37, 39);
  sum36 <= add_temp_35(37 DOWNTO 0);

  add_temp_36 <= resize(sum36, 39) + resize(product38, 39);
  sum37 <= add_temp_36(37 DOWNTO 0);

  add_temp_37 <= resize(sum37, 39) + resize(product39, 39);
  sum38 <= add_temp_37(37 DOWNTO 0);

  add_temp_38 <= resize(sum38, 39) + resize(product40, 39);
  sum39 <= add_temp_38(37 DOWNTO 0);

  add_temp_39 <= resize(sum39, 39) + resize(product41, 39);
  sum40 <= add_temp_39(37 DOWNTO 0);

  add_temp_40 <= resize(sum40, 39) + resize(product42, 39);
  sum41 <= add_temp_40(37 DOWNTO 0);

  add_temp_41 <= resize(sum41, 39) + resize(product43, 39);
  sum42 <= add_temp_41(37 DOWNTO 0);

  add_temp_42 <= resize(sum42, 39) + resize(product44, 39);
  sum43 <= add_temp_42(37 DOWNTO 0);

  add_temp_43 <= resize(sum43, 39) + resize(product45, 39);
  sum44 <= add_temp_43(37 DOWNTO 0);

  add_temp_44 <= resize(sum44, 39) + resize(product46, 39);
  sum45 <= add_temp_44(37 DOWNTO 0);

  add_temp_45 <= resize(sum45, 39) + resize(product47, 39);
  sum46 <= add_temp_45(37 DOWNTO 0);

  add_temp_46 <= resize(sum46, 39) + resize(product48, 39);
  sum47 <= add_temp_46(37 DOWNTO 0);

  add_temp_47 <= resize(sum47, 39) + resize(product49, 39);
  sum48 <= add_temp_47(37 DOWNTO 0);

  add_temp_48 <= resize(sum48, 39) + resize(product50, 39);
  sum49 <= add_temp_48(37 DOWNTO 0);

  add_temp_49 <= resize(sum49, 39) + resize(product51, 39);
  sum50 <= add_temp_49(37 DOWNTO 0);

  add_temp_50 <= resize(sum50, 39) + resize(product52, 39);
  sum51 <= add_temp_50(37 DOWNTO 0);

  add_temp_51 <= resize(sum51, 39) + resize(product53, 39);
  sum52 <= add_temp_51(37 DOWNTO 0);

  add_temp_52 <= resize(sum52, 39) + resize(product54, 39);
  sum53 <= add_temp_52(37 DOWNTO 0);

  add_temp_53 <= resize(sum53, 39) + resize(product55, 39);
  sum54 <= add_temp_53(37 DOWNTO 0);

  add_temp_54 <= resize(sum54, 39) + resize(product56, 39);
  sum55 <= add_temp_54(37 DOWNTO 0);

  add_temp_55 <= resize(sum55, 39) + resize(product57, 39);
  sum56 <= add_temp_55(37 DOWNTO 0);

  add_temp_56 <= resize(sum56, 39) + resize(product58, 39);
  sum57 <= add_temp_56(37 DOWNTO 0);

  add_temp_57 <= resize(sum57, 39) + resize(product59, 39);
  sum58 <= add_temp_57(37 DOWNTO 0);

  add_temp_58 <= resize(sum58, 39) + resize(product60, 39);
  sum59 <= add_temp_58(37 DOWNTO 0);

  add_temp_59 <= resize(sum59, 39) + resize(product61, 39);
  sum60 <= add_temp_59(37 DOWNTO 0);

  add_temp_60 <= resize(sum60, 39) + resize(product62, 39);
  sum61 <= add_temp_60(37 DOWNTO 0);

  add_temp_61 <= resize(sum61, 39) + resize(product63, 39);
  sum62 <= add_temp_61(37 DOWNTO 0);

  add_temp_62 <= resize(sum62, 39) + resize(product64, 39);
  sum63 <= add_temp_62(37 DOWNTO 0);

  add_temp_63 <= resize(sum63, 39) + resize(product65, 39);
  sum64 <= add_temp_63(37 DOWNTO 0);

  add_temp_64 <= resize(sum64, 39) + resize(product66, 39);
  sum65 <= add_temp_64(37 DOWNTO 0);

  add_temp_65 <= resize(sum65, 39) + resize(product67, 39);
  sum66 <= add_temp_65(37 DOWNTO 0);

  add_temp_66 <= resize(sum66, 39) + resize(product68, 39);
  sum67 <= add_temp_66(37 DOWNTO 0);

  add_temp_67 <= resize(sum67, 39) + resize(product69, 39);
  sum68 <= add_temp_67(37 DOWNTO 0);

  add_temp_68 <= resize(sum68, 39) + resize(product70, 39);
  sum69 <= add_temp_68(37 DOWNTO 0);

  add_temp_69 <= resize(sum69, 39) + resize(product71, 39);
  sum70 <= add_temp_69(37 DOWNTO 0);

  add_temp_70 <= resize(sum70, 39) + resize(product72, 39);
  sum71 <= add_temp_70(37 DOWNTO 0);

  add_temp_71 <= resize(sum71, 39) + resize(product73, 39);
  sum72 <= add_temp_71(37 DOWNTO 0);

  add_temp_72 <= resize(sum72, 39) + resize(product74, 39);
  sum73 <= add_temp_72(37 DOWNTO 0);

  add_temp_73 <= resize(sum73, 39) + resize(product75, 39);
  sum74 <= add_temp_73(37 DOWNTO 0);

  add_temp_74 <= resize(sum74, 39) + resize(product76, 39);
  sum75 <= add_temp_74(37 DOWNTO 0);

  add_temp_75 <= resize(sum75, 39) + resize(product77, 39);
  sum76 <= add_temp_75(37 DOWNTO 0);

  add_temp_76 <= resize(sum76, 39) + resize(product78, 39);
  sum77 <= add_temp_76(37 DOWNTO 0);

  add_temp_77 <= resize(sum77, 39) + resize(product79, 39);
  sum78 <= add_temp_77(37 DOWNTO 0);

  add_temp_78 <= resize(sum78, 39) + resize(product80, 39);
  sum79 <= add_temp_78(37 DOWNTO 0);

  add_temp_79 <= resize(sum79, 39) + resize(product81, 39);
  sum80 <= add_temp_79(37 DOWNTO 0);

  add_temp_80 <= resize(sum80, 39) + resize(product82, 39);
  sum81 <= add_temp_80(37 DOWNTO 0);

  add_temp_81 <= resize(sum81, 39) + resize(product83, 39);
  sum82 <= add_temp_81(37 DOWNTO 0);

  add_temp_82 <= resize(sum82, 39) + resize(product84, 39);
  sum83 <= add_temp_82(37 DOWNTO 0);

  add_temp_83 <= resize(sum83, 39) + resize(product85, 39);
  sum84 <= add_temp_83(37 DOWNTO 0);

  add_temp_84 <= resize(sum84, 39) + resize(product86, 39);
  sum85 <= add_temp_84(37 DOWNTO 0);

  add_temp_85 <= resize(sum85, 39) + resize(product87, 39);
  sum86 <= add_temp_85(37 DOWNTO 0);

  add_temp_86 <= resize(sum86, 39) + resize(product88, 39);
  sum87 <= add_temp_86(37 DOWNTO 0);

  add_temp_87 <= resize(sum87, 39) + resize(product89, 39);
  sum88 <= add_temp_87(37 DOWNTO 0);

  add_temp_88 <= resize(sum88, 39) + resize(product90, 39);
  sum89 <= add_temp_88(37 DOWNTO 0);

  add_temp_89 <= resize(sum89, 39) + resize(product91, 39);
  sum90 <= add_temp_89(37 DOWNTO 0);

  add_temp_90 <= resize(sum90, 39) + resize(product92, 39);
  sum91 <= add_temp_90(37 DOWNTO 0);

  add_temp_91 <= resize(sum91, 39) + resize(product93, 39);
  sum92 <= add_temp_91(37 DOWNTO 0);

  add_temp_92 <= resize(sum92, 39) + resize(product94, 39);
  sum93 <= add_temp_92(37 DOWNTO 0);

  add_temp_93 <= resize(sum93, 39) + resize(product95, 39);
  sum94 <= add_temp_93(37 DOWNTO 0);

  add_temp_94 <= resize(sum94, 39) + resize(product96, 39);
  sum95 <= add_temp_94(37 DOWNTO 0);

  add_temp_95 <= resize(sum95, 39) + resize(product97, 39);
  sum96 <= add_temp_95(37 DOWNTO 0);

  add_temp_96 <= resize(sum96, 39) + resize(product98, 39);
  sum97 <= add_temp_96(37 DOWNTO 0);

  add_temp_97 <= resize(sum97, 39) + resize(product99, 39);
  sum98 <= add_temp_97(37 DOWNTO 0);

  add_temp_98 <= resize(sum98, 39) + resize(product100, 39);
  sum99 <= add_temp_98(37 DOWNTO 0);

  add_temp_99 <= resize(sum99, 39) + resize(product101, 39);
  sum100 <= add_temp_99(37 DOWNTO 0);

  add_temp_100 <= resize(sum100, 39) + resize(product102, 39);
  sum101 <= add_temp_100(37 DOWNTO 0);

  add_temp_101 <= resize(sum101, 39) + resize(product103, 39);
  sum102 <= add_temp_101(37 DOWNTO 0);

  add_temp_102 <= resize(sum102, 39) + resize(product104, 39);
  sum103 <= add_temp_102(37 DOWNTO 0);

  add_temp_103 <= resize(sum103, 39) + resize(product105, 39);
  sum104 <= add_temp_103(37 DOWNTO 0);

  add_temp_104 <= resize(sum104, 39) + resize(product106, 39);
  sum105 <= add_temp_104(37 DOWNTO 0);

  add_temp_105 <= resize(sum105, 39) + resize(product107, 39);
  sum106 <= add_temp_105(37 DOWNTO 0);

  add_temp_106 <= resize(sum106, 39) + resize(product108, 39);
  sum107 <= add_temp_106(37 DOWNTO 0);

  add_temp_107 <= resize(sum107, 39) + resize(product109, 39);
  sum108 <= add_temp_107(37 DOWNTO 0);

  add_temp_108 <= resize(sum108, 39) + resize(product110, 39);
  sum109 <= add_temp_108(37 DOWNTO 0);

  add_temp_109 <= resize(sum109, 39) + resize(product111, 39);
  sum110 <= add_temp_109(37 DOWNTO 0);

  add_temp_110 <= resize(sum110, 39) + resize(product112, 39);
  sum111 <= add_temp_110(37 DOWNTO 0);

  add_temp_111 <= resize(sum111, 39) + resize(product113, 39);
  sum112 <= add_temp_111(37 DOWNTO 0);

  output_typeconvert <= sum112;

  -- Assignment Statements
  filter_out_stage1 <= std_logic_vector(output_typeconvert);
END rtl;
