-- -------------------------------------------------------------
--
-- Module: HPF_FIR_2
-- Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
-- Generated on: 2022-11-16 10:46:12
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: C:\Users\Elia Yfrach\Desktop\Project\Processing_Unit\Filters
-- Name: HPF_FIR_2
-- TestBenchName: Hhp2_tb
-- TestBenchStimulus: impulse step ramp chirp noise 
-- GenerateHDLTestBench: off

-- Filter Specifications:
--
-- Sample Rate     : 765.9 Hz
-- Response        : Highpass
-- Specification   : Fst,Fp,Ast,Ap
-- Stopband Edge   : 10 uHz
-- Passband Edge   : 150 Hz
-- Passband Ripple : 1 dB
-- Stopband Atten. : 40 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 7
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,15 -> [-1 1)
-- Input             : s19,0 -> [-262144 262144)
-- Filter Internals  : Full Precision
--   Output          : s35,15 -> [-524288 524288)  (auto determined)
--   Product         : s34,15 -> [-262144 262144)  (auto determined)
--   Accumulator     : s35,15 -> [-524288 524288)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY HPF_FIR_2 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(18 DOWNTO 0); -- sfix19
         filter_out                      :   OUT   std_logic_vector(34 DOWNTO 0)  -- sfix35_En15
         );

END HPF_FIR_2;


----------------------------------------------------------------
--Module Architecture: HPF_FIR_2
----------------------------------------------------------------
ARCHITECTURE rtl OF HPF_FIR_2 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(18 DOWNTO 0); -- sfix19
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(-2114, 16); -- sfix16_En15
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(-4225, 16); -- sfix16_En15
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(-6337, 16); -- sfix16_En15
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(25571, 16); -- sfix16_En15
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(-6337, 16); -- sfix16_En15
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(-4225, 16); -- sfix16_En15
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(-2114, 16); -- sfix16_En15

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 6); -- sfix19
  SIGNAL product7                         : signed(33 DOWNTO 0); -- sfix34_En15
  SIGNAL mul_temp                         : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL product6                         : signed(33 DOWNTO 0); -- sfix34_En15
  SIGNAL mul_temp_1                       : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL product5                         : signed(33 DOWNTO 0); -- sfix34_En15
  SIGNAL mul_temp_2                       : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL product4                         : signed(33 DOWNTO 0); -- sfix34_En15
  SIGNAL mul_temp_3                       : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL product3                         : signed(33 DOWNTO 0); -- sfix34_En15
  SIGNAL mul_temp_4                       : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL product2                         : signed(33 DOWNTO 0); -- sfix34_En15
  SIGNAL mul_temp_5                       : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL product1_cast                    : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL product1                         : signed(33 DOWNTO 0); -- sfix34_En15
  SIGNAL mul_temp_6                       : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL sum1                             : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL add_temp                         : signed(35 DOWNTO 0); -- sfix36_En15
  SIGNAL sum2                             : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL add_temp_1                       : signed(35 DOWNTO 0); -- sfix36_En15
  SIGNAL sum3                             : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL add_temp_2                       : signed(35 DOWNTO 0); -- sfix36_En15
  SIGNAL sum4                             : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL add_temp_3                       : signed(35 DOWNTO 0); -- sfix36_En15
  SIGNAL sum5                             : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL add_temp_4                       : signed(35 DOWNTO 0); -- sfix36_En15
  SIGNAL sum6                             : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL add_temp_5                       : signed(35 DOWNTO 0); -- sfix36_En15
  SIGNAL output_typeconvert               : signed(34 DOWNTO 0); -- sfix35_En15
  SIGNAL output_register                  : signed(34 DOWNTO 0); -- sfix35_En15


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 6) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 6) <= delay_pipeline(0 TO 5);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp(33 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_1(33 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_2(33 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_3(33 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_4(33 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_5(33 DOWNTO 0);

  product1_cast <= resize(product1, 35);

  mul_temp_6 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_6(33 DOWNTO 0);

  add_temp <= resize(product1_cast, 36) + resize(product2, 36);
  sum1 <= add_temp(34 DOWNTO 0);

  add_temp_1 <= resize(sum1, 36) + resize(product3, 36);
  sum2 <= add_temp_1(34 DOWNTO 0);

  add_temp_2 <= resize(sum2, 36) + resize(product4, 36);
  sum3 <= add_temp_2(34 DOWNTO 0);

  add_temp_3 <= resize(sum3, 36) + resize(product5, 36);
  sum4 <= add_temp_3(34 DOWNTO 0);

  add_temp_4 <= resize(sum4, 36) + resize(product6, 36);
  sum5 <= add_temp_4(34 DOWNTO 0);

  add_temp_5 <= resize(sum5, 36) + resize(product7, 36);
  sum6 <= add_temp_5(34 DOWNTO 0);

  output_typeconvert <= sum6;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
