-- -------------------------------------------------------------
--
-- Module: LPF_FIR_2_V2
-- Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
-- Generated on: 2022-12-18 10:49:12
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: C:\Users\Elia Yfrach\Desktop\Project\Processing_Unit\Filters
-- Name: LPF_FIR_2_V2
-- TestBenchName: LPF_FIR_2_V2_tb
-- TestBenchStimulus: impulse step ramp chirp noise 
-- GenerateHDLTestBench: off

-- Filter Specifications:
--
-- Sample Rate     : 4.5955 Hz
-- Response        : Lowpass
-- Specification   : Fp,Fst,Ap,Ast
-- Stopband Edge   : 800 mHz
-- Passband Edge   : 150 mHz
-- Passband Ripple : 1 dB
-- Stopband Atten. : 40 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 11
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,17 -> [-2.500000e-01 2.500000e-01)
-- Input             : s29,0 -> [-268435456 268435456)
-- Filter Internals  : Full Precision
--   Output          : s47,17 -> [-536870912 536870912)  (auto determined)
--   Product         : s44,17 -> [-67108864 67108864)  (auto determined)
--   Accumulator     : s47,17 -> [-536870912 536870912)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY LPF_FIR_2_V2 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(28 DOWNTO 0); -- sfix29
         filter_out                      :   OUT   std_logic_vector(46 DOWNTO 0)  -- sfix47_En17
         );

END LPF_FIR_2_V2;


----------------------------------------------------------------
--Module Architecture: LPF_FIR_2_V2
----------------------------------------------------------------
ARCHITECTURE rtl OF LPF_FIR_2_V2 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(28 DOWNTO 0); -- sfix29
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(1627, 16); -- sfix16_En17
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(5674, 16); -- sfix16_En17
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(10741, 16); -- sfix16_En17
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(17106, 16); -- sfix16_En17
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(21728, 16); -- sfix16_En17
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(23750, 16); -- sfix16_En17
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(21728, 16); -- sfix16_En17
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(17106, 16); -- sfix16_En17
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(10741, 16); -- sfix16_En17
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(5674, 16); -- sfix16_En17
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(1627, 16); -- sfix16_En17

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 10); -- sfix29
  SIGNAL product11                        : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp                         : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product10                        : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_1                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product9                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_2                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product8                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_3                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product7                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_4                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product6                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_5                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product5                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_6                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product4                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_7                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product3                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_8                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product2                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_9                       : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL product1_cast                    : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL product1                         : signed(43 DOWNTO 0); -- sfix44_En17
  SIGNAL mul_temp_10                      : signed(44 DOWNTO 0); -- sfix45_En17
  SIGNAL sum1                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp                         : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum2                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_1                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum3                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_2                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum4                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_3                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum5                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_4                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum6                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_5                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum7                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_6                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum8                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_7                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum9                             : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_8                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL sum10                            : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL add_temp_9                       : signed(47 DOWNTO 0); -- sfix48_En17
  SIGNAL output_typeconvert               : signed(46 DOWNTO 0); -- sfix47_En17
  SIGNAL output_register                  : signed(46 DOWNTO 0); -- sfix47_En17


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 10) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 10) <= delay_pipeline(0 TO 9);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp(43 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_1(43 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_2(43 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_3(43 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_4(43 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_5(43 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_6(43 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_7(43 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_8(43 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_9(43 DOWNTO 0);

  product1_cast <= resize(product1, 47);

  mul_temp_10 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_10(43 DOWNTO 0);

  add_temp <= resize(product1_cast, 48) + resize(product2, 48);
  sum1 <= add_temp(46 DOWNTO 0);

  add_temp_1 <= resize(sum1, 48) + resize(product3, 48);
  sum2 <= add_temp_1(46 DOWNTO 0);

  add_temp_2 <= resize(sum2, 48) + resize(product4, 48);
  sum3 <= add_temp_2(46 DOWNTO 0);

  add_temp_3 <= resize(sum3, 48) + resize(product5, 48);
  sum4 <= add_temp_3(46 DOWNTO 0);

  add_temp_4 <= resize(sum4, 48) + resize(product6, 48);
  sum5 <= add_temp_4(46 DOWNTO 0);

  add_temp_5 <= resize(sum5, 48) + resize(product7, 48);
  sum6 <= add_temp_5(46 DOWNTO 0);

  add_temp_6 <= resize(sum6, 48) + resize(product8, 48);
  sum7 <= add_temp_6(46 DOWNTO 0);

  add_temp_7 <= resize(sum7, 48) + resize(product9, 48);
  sum8 <= add_temp_7(46 DOWNTO 0);

  add_temp_8 <= resize(sum8, 48) + resize(product10, 48);
  sum9 <= add_temp_8(46 DOWNTO 0);

  add_temp_9 <= resize(sum9, 48) + resize(product11, 48);
  sum10 <= add_temp_9(46 DOWNTO 0);

  output_typeconvert <= sum10;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
