-- -------------------------------------------------------------
--
-- Module: LPF_FIR_2_V3
-- Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
-- Generated on: 2022-12-21 11:14:56
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- FIRAdderStyle: tree
-- OptimizeForHDL: on
-- TargetDirectory: C:\Users\Elia Yfrach\Desktop\Project\Processing_Unit\Filters
-- AddPipelineRegisters: on
-- Name: LPF_FIR_2_V3
-- TestBenchName: LPF_FIR_2_V3_tb
-- TestBenchStimulus: impulse step ramp chirp noise 
-- GenerateHDLTestBench: off

-- Filter Specifications:
--
-- Sample Rate     : 4.5955 kHz
-- Response        : Lowpass
-- Specification   : Fp,Fst,Ap,Ast
-- Stopband Edge   : 800 Hz
-- Passband Edge   : 150 Hz
-- Stopband Atten. : 40 dB
-- Passband Ripple : 1 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 11
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,17 -> [-2.500000e-01 2.500000e-01)
-- Input             : s8,0 -> [-128 128)
-- Filter Internals  : Full Precision
--   Output          : s26,17 -> [-256 256)  (auto determined)
--   Product         : s23,17 -> [-32 32)  (auto determined)
--   Accumulator     : s26,17 -> [-256 256)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY LPF_FIR_2_V3 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(7 DOWNTO 0); -- sfix8
         filter_out                      :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En17
         );

END LPF_FIR_2_V3;


----------------------------------------------------------------
--Module Architecture: LPF_FIR_2_V3
----------------------------------------------------------------
ARCHITECTURE rtl OF LPF_FIR_2_V3 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(7 DOWNTO 0); -- sfix8
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(1627, 16); -- sfix16_En17
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(5674, 16); -- sfix16_En17
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(10741, 16); -- sfix16_En17
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(17106, 16); -- sfix16_En17
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(21728, 16); -- sfix16_En17
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(23750, 16); -- sfix16_En17
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(21728, 16); -- sfix16_En17
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(17106, 16); -- sfix16_En17
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(10741, 16); -- sfix16_En17
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(5674, 16); -- sfix16_En17
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(1627, 16); -- sfix16_En17

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 10); -- sfix8
  SIGNAL product11                        : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp                         : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product10                        : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_1                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product9                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_2                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product8                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_3                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product7                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_4                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product6                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_5                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product5                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_6                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product4                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_7                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product3                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_8                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product2                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_9                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL product1                         : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL mul_temp_10                      : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL sum_final                        : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum1_1                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp                         : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL sumpipe1_1                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum1_2                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_1                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL sumpipe1_2                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum1_3                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_2                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL sumpipe1_3                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum1_4                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_3                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL sumpipe1_4                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum1_5                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_4                       : signed(23 DOWNTO 0); -- sfix24_En17
  SIGNAL sumpipe1_5                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sumpipe1_6                       : signed(22 DOWNTO 0); -- sfix23_En17
  SIGNAL sum2_1                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_5                       : signed(26 DOWNTO 0); -- sfix27_En17
  SIGNAL sumpipe2_1                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum2_2                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_6                       : signed(26 DOWNTO 0); -- sfix27_En17
  SIGNAL sumpipe2_2                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum2_3                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_7                       : signed(26 DOWNTO 0); -- sfix27_En17
  SIGNAL sumpipe2_3                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum3_1                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_8                       : signed(26 DOWNTO 0); -- sfix27_En17
  SIGNAL sumpipe3_1                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sumpipe3_2                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL sum4_1                           : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL add_temp_9                       : signed(26 DOWNTO 0); -- sfix27_En17
  SIGNAL sumpipe4_1                       : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL output_typeconvert               : signed(25 DOWNTO 0); -- sfix26_En17
  SIGNAL output_register                  : signed(25 DOWNTO 0); -- sfix26_En17


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 10) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 10) <= delay_pipeline(0 TO 9);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp(22 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_1(22 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_2(22 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_3(22 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_4(22 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_5(22 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_6(22 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_7(22 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_8(22 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_9(22 DOWNTO 0);

  mul_temp_10 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_10(22 DOWNTO 0);

  add_temp <= resize(product11, 24) + resize(product10, 24);
  sum1_1 <= resize(add_temp, 26);

  add_temp_1 <= resize(product9, 24) + resize(product8, 24);
  sum1_2 <= resize(add_temp_1, 26);

  add_temp_2 <= resize(product7, 24) + resize(product6, 24);
  sum1_3 <= resize(add_temp_2, 26);

  add_temp_3 <= resize(product5, 24) + resize(product4, 24);
  sum1_4 <= resize(add_temp_3, 26);

  add_temp_4 <= resize(product3, 24) + resize(product2, 24);
  sum1_5 <= resize(add_temp_4, 26);

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe1_1 <= (OTHERS => '0');
      sumpipe1_2 <= (OTHERS => '0');
      sumpipe1_3 <= (OTHERS => '0');
      sumpipe1_4 <= (OTHERS => '0');
      sumpipe1_5 <= (OTHERS => '0');
      sumpipe1_6 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe1_1 <= sum1_1;
        sumpipe1_2 <= sum1_2;
        sumpipe1_3 <= sum1_3;
        sumpipe1_4 <= sum1_4;
        sumpipe1_5 <= sum1_5;
        sumpipe1_6 <= product1;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  add_temp_5 <= resize(sumpipe1_1, 27) + resize(sumpipe1_2, 27);
  sum2_1 <= add_temp_5(25 DOWNTO 0);

  add_temp_6 <= resize(sumpipe1_3, 27) + resize(sumpipe1_4, 27);
  sum2_2 <= add_temp_6(25 DOWNTO 0);

  add_temp_7 <= resize(sumpipe1_5, 27) + resize(sumpipe1_6, 27);
  sum2_3 <= add_temp_7(25 DOWNTO 0);

  temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe2_1 <= (OTHERS => '0');
      sumpipe2_2 <= (OTHERS => '0');
      sumpipe2_3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe2_1 <= sum2_1;
        sumpipe2_2 <= sum2_2;
        sumpipe2_3 <= sum2_3;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  add_temp_8 <= resize(sumpipe2_1, 27) + resize(sumpipe2_2, 27);
  sum3_1 <= add_temp_8(25 DOWNTO 0);

  temp_process3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe3_1 <= (OTHERS => '0');
      sumpipe3_2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe3_1 <= sum3_1;
        sumpipe3_2 <= sumpipe2_3;
      END IF;
    END IF; 
  END PROCESS temp_process3;

  add_temp_9 <= resize(sumpipe3_1, 27) + resize(sumpipe3_2, 27);
  sum4_1 <= add_temp_9(25 DOWNTO 0);

  temp_process4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe4_1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe4_1 <= sum4_1;
      END IF;
    END IF; 
  END PROCESS temp_process4;

  sum_final <= sumpipe4_1;

  output_typeconvert <= sum_final;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
